### ISSUE TITLE
EditText Is Not Clickable

### ISSUE THREAD

**Issue by ChristophyBarth** [simformsolutions/CustomEditTextOutLineBorder#23]
The edit text isn't clickable. I hope you don't mind going through the views used to resolve this.

**Comment by MSajidJuneja** [comment]
@chrisbarth01 Can you describe the issue in detail?

**Comment by ChristophyBarth** [comment]
@MSajidJuneja The setonclicklisterner that works for any widget.

**Comment by yashwantgowla-simform** [comment]
@chrisbarth01 Issue resolved. You will get new update in the next release.

**Comment by ChristophyBarth** [comment]
Cheers man.
