### ISSUE TITLE
addTextChangeListener

### ISSUE THREAD

**Issue by ChristophyBarth** [simformsolutions/CustomEditTextOutLineBorder#24]
Great stuff you've created here!

It is very common that people could want to attach an addTextChangeListener. I see that SSCustomEdittextOutlinedBorder is a view but not directly an edittext view, which is why it doesn't have other default edittext features. I'd suggest that you add a method that returns the main edittext (for example `username_tv.edittext`). This way, people can directly access the edittext. But if that will be too heavy, you could add a method that returns the addTextChangeListener (which I and many people need), and probably some commonly used methods. Because we are limited to the methods you've provided.

**Comment by yashwantgowla-simform** [comment]
@chrisbarth01 Thanks for the suggestion. TextChangeListener feature has been added now. You will get new update in the next release.

**Comment by Mustafa74Dev** [comment]
Can we Have example of Textwatcher
